import { Callout, PageHeader, Pager } from "../../../../components/docs/prose";

export const metadata = { title: "Distributed Runtime" };
export default function DistributedRuntimeDocs() { return <div className="docs-prose">
  <PageHeader eyebrow="Engine" title="Distributed runtime" lead="Validated stage DAGs, versioned fragments, deterministic partitioning, authenticated Arrow exchange, retry, and cancellation form the current distributed alpha." />
  <h2>Query shapes</h2><table><thead><tr><th>Shape</th><th>Evidence</th></tr></thead><tbody>
    <tr><td>Scan/filter/project</td><td>Distributed and Docker-verified locally</td></tr><tr><td>Aggregate</td><td>Partial/final weighted AVG and exact distinct transport</td></tr><tr><td>Sort/TopN</td><td>Partial/final execution with bounded spill merge</td></tr><tr><td>Inner equi-join</td><td>Hash repartition and broadcast planning; distributed differential coverage</td></tr><tr><td>Left/right/full equi-join</td><td>Representative server-level differential cases pass; broader skew, failure, and sustained-concurrency qualification remains</td></tr><tr><td>Cross join</td><td>Representative server-level differential case passes; it uses one partition and fails closed when the build cannot fit memory</td></tr>
  </tbody></table>
  <h2>How a distributed query moves</h2><p>The coordinator resolves a version-pinned catalog snapshot, builds a stage graph, and assigns validated fragments to workers. Scan and partial operators run close to the files. Hash repartition exchanges Arrow batches by join or grouping key; a single final stage merges the partitions when global ordering or aggregation requires it. A broadcast plan is used only when the build side satisfies the memory contract.</p>
  <p>Join conditions currently require equality keys for repartitioning. Cross joins deliberately use one partition and fail closed when the build cannot fit the reserved memory; this protects correctness and prevents an accidental all-to-all explosion.</p>
  <h2>Exchange and recovery</h2><p>Arrow IPC v2 identifies query, stage, exchange, attempt, and partition. Authenticated stores enforce byte/count ceilings and idempotency. Retry rotates attempts, stale work fails closed, cancellation propagates, and cleanup releases state. The executor has dedicated tests for nulls, duplicates, skew, spill, inner/outer/cross semantics, and memory cleanup; server-level representative join qualification now passes.</p>
  <Callout type="warn">Streaming exchange, durable spooling, skew mitigation, cost-based distribution, admission/resource groups, and sustained worker-loss/concurrency evidence remain production gates. These are the differences that still separate the current alpha from a Trino- or ClickHouse-class production runtime.</Callout>
  <h2>Capability boundary</h2><p>Kaveon owns the SQL parser, planner, Arrow operators, catalog resolution, exchange protocol, and memory accounting. It does not embed Trino, ClickHouse, Spark, or DuckDB. A capability is promoted only after parser, planner, physical execution, distributed fragments, correctness tests, and operational evidence agree; a passing local operator test alone does not make a distributed feature production-ready.</p>
  <h2>Roadmap to production-class distribution</h2><table><thead><tr><th>Workstream</th><th>Why it matters</th><th>Current position</th></tr></thead><tbody>
    <tr><td>Cost-based and adaptive planning</td><td>Choose broadcast, repartition, join order, and runtime strategies from exact statistics</td><td>Statistics and distribution hooks exist; broad join enumeration and adaptive reordering remain open</td></tr>
    <tr><td>Fault-tolerant exchange</td><td>Recover a failed worker without restarting the whole query</td><td>Attempt identity, retry, stale-output rejection, cancellation, and cleanup exist; durable external spooling and sustained worker-loss evidence remain</td></tr>
    <tr><td>Vectorized scan and decode</td><td>Keep CPU cost proportional to selected columns and surviving row groups</td><td>Arrow batches, projection, predicate pushdown, and row-group pruning exist; cloud-scale decode qualification remains</td></tr>
    <tr><td>Join and aggregation scale</td><td>Stay exact under skew, high cardinality, and bounded memory</td><td>Hash repartition, broadcast planning, spill, skew guards, and exact merge paths exist; broader benchmark qualification remains</td></tr>
    <tr><td>Operational controls</td><td>Protect shared clusters under concurrency</td><td>Admission and memory accounting exist; resource groups, workload isolation, and autoscaling evidence remain</td></tr>
  </tbody></table>
  <Pager prev={{ href: "/docs/engine/sql", title: "Engine SQL" }} next={{ href: "/docs/engine/storage", title: "Storage & Catalogs" }} />
</div>; }
