import { Callout, PageHeader, Pager } from "../../../../components/docs/prose";

export const metadata = { title: "Distributed Runtime" };
export default function DistributedRuntimeDocs() { return <div className="docs-prose">
  <PageHeader eyebrow="Engine" title="Distributed runtime" lead="Validated stage DAGs, versioned fragments, deterministic partitioning, authenticated Arrow exchange, retry, and cancellation form the current distributed alpha." />
  <h2>Query shapes</h2><table><thead><tr><th>Shape</th><th>Evidence</th></tr></thead><tbody>
    <tr><td>Scan/filter/project</td><td>Distributed and Docker-verified locally</td></tr><tr><td>Aggregate</td><td>Partial/final weighted AVG and exact distinct transport</td></tr><tr><td>Sort/TopN</td><td>Partial/final execution with bounded spill merge</td></tr><tr><td>Inner equi-join</td><td>Hash repartition and broadcast planning; distributed differential coverage</td></tr><tr><td>Left/right/full equi-join</td><td>Physical executor and local semantics are covered; distributed qualification is an explicit alpha gate</td></tr><tr><td>Cross join</td><td>Physical executor and local semantics are covered; distributed qualification is an explicit alpha gate and requires bounded build memory</td></tr>
  </tbody></table>
  <h2>How a distributed query moves</h2><p>The coordinator resolves a version-pinned catalog snapshot, builds a stage graph, and assigns validated fragments to workers. Scan and partial operators run close to the files. Hash repartition exchanges Arrow batches by join or grouping key; a single final stage merges the partitions when global ordering or aggregation requires it. A broadcast plan is used only when the build side satisfies the memory contract.</p>
  <p>Join conditions currently require equality keys for repartitioning. Cross joins deliberately use one partition and fail closed when the build cannot fit the reserved memory; this protects correctness and prevents an accidental all-to-all explosion.</p>
  <h2>Exchange and recovery</h2><p>Arrow IPC v2 identifies query, stage, exchange, attempt, and partition. Authenticated stores enforce byte/count ceilings and idempotency. Retry rotates attempts, stale work fails closed, cancellation propagates, and cleanup releases state. The executor has dedicated tests for nulls, duplicates, skew, spill, inner/outer/cross semantics, and memory cleanup; server-level distributed qualification is tracked separately.</p>
  <Callout type="warn">Streaming exchange, durable spooling, skew mitigation, cost-based distribution, admission/resource groups, and sustained worker-loss/concurrency evidence remain production gates. These are the differences that still separate the current alpha from a Trino- or ClickHouse-class production runtime.</Callout>
  <h2>Capability boundary</h2><p>Kaveon owns the SQL parser, planner, Arrow operators, catalog resolution, exchange protocol, and memory accounting. It does not embed Trino, ClickHouse, Spark, or DuckDB. A capability is promoted only after parser, planner, physical execution, distributed fragments, correctness tests, and operational evidence agree; a passing local operator test alone does not make a distributed feature production-ready.</p>
  <Pager prev={{ href: "/docs/engine/sql", title: "Engine SQL" }} next={{ href: "/docs/engine/storage", title: "Storage & Catalogs" }} />
</div>; }
