[package]
name = "kaveon-cli"
description = "Kaveon Engine CLI — interactive SQL shell"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "kaveon"
path = "src/main.rs"

[dependencies]
kaveon-core = { path = "../core" }
kaveon-exec = { path = "../exec" }
kaveon-optim = { path = "../optim" }
kaveon-sql = { path = "../sql" }
kaveon-storage = { path = "../storage" }
arrow = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { workspace = true }
serde_json = { workspace = true }
