[package]
name = "kaveon-server"
description = "Kaveon Engine server — coordinator and worker nodes"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "kaveon-server"
path = "src/main.rs"

[dependencies]
kaveon-core = { path = "../core" }
kaveon-catalog = { path = "../catalog" }
kaveon-exec = { path = "../exec" }
kaveon-optim = { path = "../optim" }
kaveon-sql = { path = "../sql" }
kaveon-storage = { path = "../storage" }
arrow = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
uuid = { workspace = true }
reqwest = { workspace = true }
toml = { workspace = true }
anyhow = { workspace = true }
sha2 = "0.10"
axum-server = { version = "0.8", features = ["tls-rustls-no-provider"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
futures = { workspace = true }
libc = "0.2"
jsonwebtoken = { version = "10.3", features = ["rust_crypto"] }

[dev-dependencies]
parquet = { workspace = true }
rsa = "0.9"
rand = "0.8"
base64 = "0.22"
object_store = { workspace = true }
